M48
; DRILL file {KiCad 7.0.6} date Sun Mar 10 00:39:46 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-10T00:39:46+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.0245Y-3.3661
X5.0245Y-4.5669
X6.7913Y-3.3661
X6.7913Y-4.5669
T0
M30
